- name: copy template
  unarchive: src=tomcat-template.tar.gz dest=/usr/src
- name: 创建项目{{ project }}
  file: path={{ tomcat_dir }} state=directory force=yes
- name: 判断模块{{ module }}是否已经存在，如果存在则删除
  stat: path={{ tomcat_root }}
  register: reg
- name: 删除旧版本的模块{{ module }}
  file: path={{ tomcat_root }} state=absent
  when: reg.stat.exists
- name: 创建项目{{ project }}模块{{ module }}
  command: cp -r  /usr/src/tomcat-template/ "{{ tomcat_root }}"
- name: 生成catalina.sh
  template: src=catalina.j2 dest={{ tomcat_root }}/bin/catalina.sh
- name: 生成server.xml
  template: src=server.j2 dest={{ tomcat_root }}/conf/server.xml
- name: 设置属组
  file: path={{ tomcat_dir }} recurse=yes owner=qsc_user group=qsc_user